name: Bug report 2
title: 'This is the Title'

description: A custom form!
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug!
      description: This is an extra description.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: error-message
    attributes:
      label: The error
      description: Copy-paste the error code you see in the terminal (as much as you can) here
      render: bash
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment
      description: |
        examples:
          - **OS**: Ubuntu 20.04
          - **Node**: 13.14.0
          - **npm**: 7.6.3
      value: |
          - OS:
          - Node:
          - npm:
      render: markdown
