name: Bug report 2
title: 'This is the Title'

description: A custom form!
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug!
      description: This is an extra description.
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
