name: Bug report 2
about: Create a report to help us improve!
title: 'This is the Title'
labels: ''
assignees: ''

description: A custom form!
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug!
      description: This is an extra description.
      placeholder: A clear and concise description of what the bug is.
      
    validations:
      required: true
